import React from 'react';
import { Inter } from 'next/font/google';
import './globals.css';
import Authprovider from '../component/Authprovider'

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title:'Create Next App',
  description: 'Generated by create next app'
}

const Layout = ({
  children,
}: {
  children: React.ReactNode
}) => {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Authprovider>
          {children}
        </Authprovider>
       </body>
    </html>
  )
}

export default Layout;